import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/header'
import Footer from './components/footer'
//import 'bootstrap/dist/css/bootstrap.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next by WP Rest',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
<body data-bs-theme="dark">
<Header />

     <main className={inter.className}>
       {children}

    </main>
<Footer />
</body>
    </html>
  )
}
